package fancybank.gui;

import java.util.ArrayList;

import fancybank.account.CheckAccount;
import fancybank.account.SavingAccount;
import fancybank.account.SecurityAccount;
import fancybank.currency.Currency;
import fancybank.data.Data;
import fancybank.user.Customer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author xiekangxian Di Wang
 */
public class CustomerMainPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMainPage
     */
	Customer c;
    public CustomerMainPage(Customer customer) {
        initComponents();
        this.c = customer;
        this.nickname_text.setText(c.getUsername().get());
        ArrayList<CheckAccount> checks = c.getCheckAccount();
        ArrayList<Currency> all_uncreated = new ArrayList<Currency>();
        ArrayList<Currency> all_currency = Data.getInstance().getCurrencyList();
        for(int i=0;i<checks.size();i++) {
        	CheckAccount acc = checks.get(i);
        	this.checking_acc_selector.addItem("CheckingAccount:"+acc.getAccountNumber()+": "+acc.getBalance().getCurrency().getName());
        }
        //int number_currency_exist = ;
        
        for(int i =0;i<all_currency.size();i++) {
        	Currency c = all_currency.get(i);
        	boolean exist = false;
        	for(int j=0;j<checks.size();j++) {
            	  if(checks.get(j).getBalance().getCurrency().getSymbol().equals(c.getSymbol())) {
            		  exist = true;
            	  } 
        	}
        	if(exist)continue;
        	this.checking_acc_selector.addItem("Uncreated Currency:"+c.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JLabel nickname_noti = new javax.swing.JLabel();
        nickname_text = new javax.swing.JTextField();
        saving_button = new javax.swing.JButton();
        security_button = new javax.swing.JButton();
        transaction_button = new javax.swing.JButton();
        logoff_button = new javax.swing.JButton();
        info_button = new javax.swing.JButton();
        transfer_button = new javax.swing.JButton();
        checking_acc_selector = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Main Menu");

        nickname_noti.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        nickname_noti.setText("NickName :");

        nickname_text.setEditable(false);
        nickname_text.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        saving_button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        saving_button.setText("Saving Account");
        saving_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saving_buttonActionPerformed(evt);
            }
        });

        security_button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        security_button.setText("Security Account");
        security_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                security_buttonActionPerformed(evt);
            }
        });

        transaction_button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        transaction_button.setText("View Transactions");
        transaction_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaction_buttonActionPerformed(evt);
            }
        });

        logoff_button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        logoff_button.setText("Log off");
        logoff_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoff_buttonActionPerformed(evt);
            }
        });

        info_button.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        info_button.setText("info");
        info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_buttonActionPerformed(evt);
            }
        });


        transfer_button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        transfer_button.setText("Make Transfer");
        transfer_button.setActionCommand("");
        transfer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfer_buttonActionPerformed(evt);
            }
        });

        submit.setText("✔");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(nickname_noti, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(nickname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(254, 254, 254)
                                                .addComponent(logoff_button, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 122, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(checking_acc_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(saving_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(security_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(transfer_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(transaction_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(199, 199, 199))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(info_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nickname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nickname_noti))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(checking_acc_selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(saving_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(security_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(transfer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(transaction_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(logoff_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checking_acc_selector, saving_button});

        pack();
    }// </editor-fold>

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checking_buttonActionPerformed
        // TODO add your handling code here:
        int ind = this.checking_acc_selector.getSelectedIndex();
        String selected = String.valueOf(this.checking_acc_selector.getSelectedItem());
        Customer c = this.c;
        this.setVisible(false);
        dispose();
        if(ind>=this.c.getCheckAccount().size()) {
        	//create one more checking account
        	String cur = selected.substring(selected.length()-3,selected.length());
        	this.c.createCheckAccount(0, cur);
        	this.c.save();
        	java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new CustomerMainPage(c).setVisible(true);
                }
            });
        }
        else {
        	java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new CheckingAccountPage(c,ind).setVisible(true);
                }
            });
        }
        
        //aa
    }//GEN-LAST:event_checking_buttonActionPerformed

    private void checking_acc_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checking_acc_selectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checking_acc_selectorActionPerformed

    private void saving_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_saving_buttonActionPerformed
        // TODO add your handling code here:
    	Customer c = this.c;
    	this.setVisible(false);
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SavingAccountPage(c).setVisible(true);
            }
        });
    }// GEN-LAST:event_saving_buttonActionPerformed

    private void transaction_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_transaction_buttonActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionsPage(c).setVisible(true);
            }
        });
    }// GEN-LAST:event_transaction_buttonActionPerformed

    private void security_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_security_buttonActionPerformed
        // TODO add your handling code here:
    	Customer c = this.c;
    	this.setVisible(false);
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecurityAccountPage(c).setVisible(true);
            }
        });
        
    }// GEN-LAST:event_security_buttonActionPerformed

    private void logoff_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoff_buttonActionPerformed
        // TODO add your handling code here:
    	this.setVisible(false);
        dispose();
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
                
            }
        });
    }// GEN-LAST:event_logoff_buttonActionPerformed

    private void info_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_info_buttonActionPerformed
        // TODO add your handling code here:
    	Customer c = this.c;
    	System.out.println("info pressed!!!");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInformationPage(c).setVisible(true);
            }
        });
    }// GEN-LAST:event_info_buttonActionPerformed


    private void transfer_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_transfer_buttonActionPerformed
        // TODO add your handling code here:
    	Customer c = this.c;
    	this.setVisible(false);
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferPage(c).setVisible(true);
            }
        });
    }// GEN-LAST:event_transfer_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        
        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerMainPage().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> checking_acc_selector;
    private javax.swing.JButton info_button;
    private javax.swing.JButton logoff_button;
    private javax.swing.JTextField nickname_text;
    private javax.swing.JButton saving_button;
    private javax.swing.JButton security_button;
    private javax.swing.JButton submit;
    private javax.swing.JButton transaction_button;
    private javax.swing.JButton transfer_button;
    // End of variables declaration//GEN-END:variables
}
