package fancybank.gui;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;

import fancybank.account.SecurityAccount;
import fancybank.data.Data;
import fancybank.stock.Stock;
import fancybank.user.Customer;

/**
 *
 * @author xiekangxian Di Wang
 */
public class StockOperationPage extends javax.swing.JFrame {

    /**
     * Creates new form StockOperationPage
     */
	private Customer c;
	private SecurityAccount account;
    public StockOperationPage(Customer c, SecurityAccount account) {
        initComponents();
        this.c = c;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel stock_number_noti = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        stock_number_text = new javax.swing.JTextField();
        share_amount_text = new javax.swing.JTextField();
        buy_button = new javax.swing.JButton();
        sell_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trade Stock");

        stock_number_noti.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        stock_number_noti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stock_number_noti.setText("Stock Name :");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Share Amount :");

        stock_number_text.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        stock_number_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stock_number_textKeyTyped(evt);
            }
        });

        share_amount_text.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        share_amount_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                share_amount_textKeyTyped(evt);
            }
        });

        buy_button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        buy_button.setText("Buy");
        buy_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_buttonActionPerformed(evt);
            }
        });

        sell_button.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        sell_button.setText("Sell");
        sell_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_buttonActionPerformed(evt);
            }
        });

        back_button.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        back_button.setText("Back");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(buy_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(sell_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stock_number_noti, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stock_number_text)
                            .addComponent(share_amount_text, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stock_number_noti, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stock_number_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(share_amount_text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sell_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {share_amount_text, stock_number_text});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, stock_number_noti});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sell_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sell_buttonActionPerformed
    	String stock_number = this.stock_number_text.getText();
        String share = this.share_amount_text.getText();
        
        Stock s = Data.getInstance().getStockMarket().getStock(stock_number);
        if(s==null) {
        	this.stock_number_text.setText("");
            this.share_amount_text.setText("");
            JOptionPane.showMessageDialog(this, "This stock doesn't exist!", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        	return;
        }
        
        this.stock_number_text.setText("");
        this.share_amount_text.setText("");
        setVisible(false);
        dispose();
        Double profit = this.account.sellStock(stock_number, Integer.parseInt(share));
        JOptionPane.showMessageDialog(this, "Your realized profit is: "+String.valueOf(profit),
                "INFORMATION",
                JOptionPane.INFORMATION_MESSAGE);
        Customer c = this.c;
        c.save();
        SecurityAccount account = this.account;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnStockPage(c,account).setVisible(true);
            }
        });

    }// GEN-LAST:event_sell_buttonActionPerformed

    private void stock_number_textKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_stock_number_textKeyTyped
        // TODO add your handling code here:
        
    }// GEN-LAST:event_stock_number_textKeyTyped

    private void share_amount_textKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_share_amount_textKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if ((!(Character.isDigit(enter))) && enter != '.') {
            evt.consume();
        }
    }// GEN-LAST:event_share_amount_textKeyTyped

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }// GEN-LAST:event_back_buttonActionPerformed

    private void buy_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buy_buttonActionPerformed
    	String stock_number = this.stock_number_text.getText();
        String share = this.share_amount_text.getText();
        Stock s = Data.getInstance().getStockMarket().getStock(stock_number);
        if(s==null) {
        	this.stock_number_text.setText("");
            this.share_amount_text.setText("");
            JOptionPane.showMessageDialog(this, "This stock doesn't exist!", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        	return;
        }
        this.stock_number_text.setText("");
        this.share_amount_text.setText("");
        setVisible(false);
        dispose();
        this.account.buyStock(stock_number, Integer.parseInt(share));
        this.c.save();
        Customer c = this.c;
        SecurityAccount acc = this.account;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnStockPage(c,account).setVisible(true);
            }
        });

    }// GEN-LAST:event_buy_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockOperationPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockOperationPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockOperationPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockOperationPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockOperationPage().setVisible(true);
            }
        });
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton buy_button;
    private javax.swing.JButton sell_button;
    private javax.swing.JTextField share_amount_text;
    private javax.swing.JTextField stock_number_text;
    // End of variables declaration//GEN-END:variables
}
